---
#Начало файла provision.yml
- name: OSPF
  #Указываем имя хоста или группу, которые будем настраивать
  hosts: all
  #Параметр выполнения модулей от root-пользователя
  become: yes
  #Указание файла с дополнителыми переменными (понадобится при добавлении темплейтов)
  #vars_files:
  #  - defaults/main.yml
  tasks:
  # Обновление пакетов и установка vim, traceroute, tcpdump, net-tools
  - name: set up OSPF
    template:
      src: frr-{{ansible_hostname}}-task3.conf
      dest: /etc/frr/frr.conf
      owner: frr
      group: frr
      mode: 0640
    when: (ansible_hostname == "router2")

  - name: restart FRR
    service:
      name: frr
      state: restarted
      enabled: true
