# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant.configure(2) do |config|
   config.vm.box = "centos7"
 
 config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
end
 config.vm.define "systemd" do |nfss|
    nfss.vm.network "private_network", ip: "192.168.50.10",
virtualbox__intnet: "net1"
    nfss.vm.hostname = "nfss"
    nfss.vm.provision "shell", path: "initscript.sh"
end
 
 
end
